# Generated by Django 5.0 on 2024-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bathroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='bedroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
