# Generated by Django 5.0 on 2024-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channel_chat_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='updataed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
