# Generated by Django 5.0 on 2024-01-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_channel_updataed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='updataed_at',
            new_name='updated_at',
        ),
    ]
